name: ci-cd

on:
  push:
    branches:
      - main

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Write GH env 
      run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install
    
    - name: Test with pytest
      run: poetry run pytest tests/ --cov=overviewpy --cov-report=xml

    - name: Use Codecov to track coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml   # coverage report

#    - name: Build documentation
#      run: poetry run make html --directory docs/
    - name: Generate mkdocs 
      uses: actions/cache@v3
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-
      run: pip install \
            mkdocs-material \
            mkdocstrings \
            mkdocs-jupyter \
            md_in_html \
            markdown_include 
      run: mkdocs gh-deploy --force